// apps/frontend/src/app/add-product-dialog/add-product-dialog.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, ElementRef, EventEmitter, Input, OnInit, Output, Renderer2 } from '@angular/core';
import { Observable } from 'rxjs';
import { ProductDetails, ProductSearchResult, ProductSearchResults, SearchResultItem } from '@shoppi/api-interfaces';

export interface AddProductData {
  productId: string;
  combinedTrackingId: string | null;
  conversion: {
    fromQuantity: number;
    fromUnit: string;
    toQuantity: number;
    toUnit: string;
  } | null;
}

@Component({
  selector: 'app-add-product-dialog',
  templateUrl: './add-product-dialog.component.html',
  styleUrls: ['./add-product-dialog.component.scss'],
})
export class AddProductDialogComponent implements OnInit {
  @Input()
  public item!: SearchResultItem;

  @Output()
  public exit: EventEmitter<void> = new EventEmitter();

  @Output()
  public addProduct: EventEmitter<AddProductData> = new EventEmitter();

  public product$!: Observable<ProductDetails>;

  public searchItemName: string;
  public results: ProductSearchResult[];
  public searchComplete: boolean;
  public mustProvideConversion: boolean;
  public conversion: {
    fromUnit: string;
    fromQuantity: number;
    toQuantity: number;
    toUnit: string;
  } = {
    fromUnit: '',
    fromQuantity: 1,
    toQuantity: 1,
    toUnit: '',
  };

  public get combineWithItem(): ProductSearchResult | null {
    return this._combineWithItem;
  }

  public set combineWithItem(value: ProductSearchResult | null) {
    this._combineWithItem = value;

    if (!value) {
      this.searchItemName = '';
      this.results = [];
    }

    if (value) {
      this.product$.subscribe((product) => {
        this.mustProvideConversion = !value.units.includes(product.unitName);
        this.conversion.fromUnit = value.units[0];
        this.conversion.toUnit = product.unitName;
      });
    }
  }

  private _combineWithItem: ProductSearchResult | null;

  constructor(
    private readonly elementRef: ElementRef,
    private readonly renderer: Renderer2,
    private readonly http: HttpClient
  ) {
    this.searchItemName = '';
    this.results = [];
    this.searchComplete = false;
    this._combineWithItem = null;
    this.mustProvideConversion = false;

    renderer.listen(elementRef.nativeElement, 'click', (event: MouseEvent) => {
      if (event.target === elementRef.nativeElement) {
        this.exit.emit();
      }
    });
  }

  public ngOnInit(): void {
    // TODO move this out of this component, it should be loaded before the popup opens
    this.product$ = this.http.get<ProductDetails>(`/api/products/${this.item.id}`);
    this.search(this.item.name);
  }

  public onAdd(): void {
    this.addProduct.emit({
      productId: this.item.id,
      combinedTrackingId: this._combineWithItem?.trackingId ?? null,
      conversion: this.mustProvideConversion ? this.conversion : null,
    });
  }

  public onClose(): void {
    this.exit.emit();
  }

  public onSearchTextChange(searchText: string): void {
    this.searchItemName = searchText;

    if (searchText.length <= 2) {
      this._combineWithItem = null;
      this.searchComplete = false;
      return;
    }

    this.search(searchText);
  }

  private search(searchText: string): void {
    this.http
      .get<ProductSearchResults>('/api/price-comparisons/search', {
        params: {
          term: searchText,
        },
      })
      .subscribe(({ results }) => {
        this._combineWithItem = null;
        this.results = results;
        this.searchComplete = true;
      });
  }
}

<div class="add-product-dialog">
  <button class="add-product-dialog__close" (click)="onClose()" style="cursor: pointer">
    Close
  </button>

  <ng-template #loading>
    <div class="add-product-dialog__content">
      Loading...
    </div>
  </ng-template>
  <ng-container *ngIf="product$ | async as product; else loading">
    <div class="add-product-dialog__content">
      <h1>Add Item</h1>
      <h2>{{ product.name }} - {{ product.price | currency:'GBP' }}</h2>
      <p>{{ product.supermarket }}</p>
      <div style="margin-top: 1rem">
        Combine with existing item
        <ng-container *ngIf="!combineWithItem; else selectedItem">
          <input
            type="text"
            placeholder="Enter item name"
            [ngModel]="searchItemName"
            (ngModelChange)="onSearchTextChange($event)"
          />
          <ul *ngIf="results">
            <li *ngFor="let result of results">
              <button
                class="add-product-dialog__search-result button-link"
                (click)="combineWithItem = result"
              >{{ result.name }}</button>
            </li>
          </ul>
          <p *ngIf="searchComplete && !results.length">No results found</p>
        </ng-container>
        <ng-template #selectedItem>
          <p style="margin-left: 1rem">{{ combineWithItem!.name }}
            <button (click)="combineWithItem = null">Clear</button>
          </p>
          <div *ngIf="mustProvideConversion">
            <label>How does this item convert?</label><br>
            <input type="number" style="width: 50px" [(ngModel)]="conversion.fromQuantity" />
            <select [(ngModel)]="conversion.fromUnit">
              <option *ngFor="let unit of combineWithItem!.units" [value]="unit">
                {{ unit }}
              </option>
            </select>
            =
            <input type="number" style="width: 50px" [(ngModel)]="conversion.toQuantity" />
            {{ product.unitName }}
          </div>
        </ng-template>
      </div>

      <div class="add-product-dialog__buttons">
        <button class="add-product-dialog__button" (click)="onClose()">Cancel</button>
        <button class="add-product-dialog__button" type="submit" (click)="onAdd()">Add</button>
      </div>
    </div>
  </ng-container>
</div>

// src/routes/search/AddProductDialog.svelte
<script module lang="ts">
  export interface AddProductData {
    productId: string;
    combinedTrackingId: string | null;
    conversion: {
      fromQuantity: number;
      fromUnit: string;
      toQuantity: number;
      toUnit: string;
    } | null;
  }
</script>

<script lang="ts">
  import type {
    ProductDetails,
    ProductSearchResult,
    SearchResultItem,
  } from '$lib/models';
  import { clickOutside } from 'svelte-outside';
  import { formatCurrency } from '$lib/util/format';
  import { onMount } from 'svelte';

  interface Props {
    item: SearchResultItem;
    onExit: () => void;
    onAddProduct: (data: AddProductData) => void;
  }

  console.log('APD created');

  let { item, onExit, onAddProduct }: Props = $props();

  let isMounted: boolean = false;

  let product: ProductDetails | null = $state(null);
  let results: ProductSearchResult[] = $state([]);
  let combineWithItem: ProductSearchResult | null = $state(null);
  let searchComplete: boolean = $state(false);
  let searchItemName: string = $state('');
  let mustProvideConversion: boolean = $state(false);
  let conversion: {
    fromUnit: string;
    fromQuantity: number;
    toQuantity: number;
    toUnit: string;
  } = $state({
    fromUnit: '',
    fromQuantity: 1,
    toQuantity: 1,
    toUnit: '',
  });

  $effect(() => {
    (async () => {
      product = await (await fetch(`/api/products/${item.id}`)).json();
      await search(item.name);
    })();
  });

  async function search(searchText: string): Promise<void> {
    const res = await fetch(
      `/api/price-comparisons/search?${new URLSearchParams({ term: searchText }).toString()}`
    );
    results = (await res.json()).results;

    combineWithItem = null;
    searchComplete = true;
  }

  onMount(() => {
    setTimeout(() => {
      isMounted = true;
    });
  });

  function close(): void {
    if (isMounted) {
      onExit();
    }
  }

  $effect(() => {
    if (searchItemName?.length <= 2) {
      combineWithItem = null;
      searchComplete = false;
      results = [];
      return;
    }

    search(searchItemName);
  });

  function setCombineWithItem(item: ProductSearchResult | null): void {
    setTimeout(() => {
      if (!product) {
        return;
      }

      combineWithItem = item;

      if (combineWithItem) {
        mustProvideConversion = !combineWithItem.units.includes(
          product.unitName
        );
        conversion = {
          ...conversion,
          fromUnit: combineWithItem.units[0],
          toUnit: product.unitName,
        };
      } else {
        searchItemName = '';
        results = [];
      }
    });
  }

  function onAdd(): void {
    onAddProduct({
      productId: item.id,
      combinedTrackingId: combineWithItem?.trackingId ?? null,
      conversion: mustProvideConversion ? conversion : null,
    });
  }
</script>

<div class="add-product-dialog">
  <div class="add-product-dialog__wrapper" use:clickOutside={close}>
    <button
      class="add-product-dialog__close"
      onclick={close}
      style="cursor: pointer"
      >Close
    </button>

    {#if !product}
      <div class="add-product-dialog__content">Loading...</div>
    {:else}
      <div class="add-product-dialog__content">
        <h1>Add Item</h1>
        <h2>{product.name} - {formatCurrency(product.price)}</h2>
        <p>{product.supermarket}</p>
        <div style="margin-top: 1rem">
          Combine with existing item
          {#if !combineWithItem}
            <input
              type="text"
              placeholder="Enter item name"
              bind:value={searchItemName}
            />
            {#if results}
              <ul>
                {#each results as result}
                  <li>
                    <button
                      class="add-product-dialog__search-result button-link"
                      onclick={() => setCombineWithItem(result)}
                    >
                      {result.name}
                    </button>
                  </li>
                {/each}
              </ul>
            {/if}
            {#if searchComplete && !results.length}
              <p>No results found</p>
            {/if}
          {:else}
            <p style="margin-left: 1rem">
              {combineWithItem.name}
              <button onclick={() => setCombineWithItem(null)}>Clear</button>
            </p>
            {#if mustProvideConversion}
              <div>
                <label for="conversion.from">How does this item convert?</label
                ><br />
                <input
                  id="conversion.from"
                  type="number"
                  style="width: 50px"
                  bind:value={conversion.fromQuantity}
                />
                <select bind:value={conversion.fromUnit}>
                  {#each combineWithItem.units as unit}
                    <option value={unit}>
                      {unit}
                    </option>
                  {/each}
                </select>
                =
                <input
                  type="number"
                  style="width: 50px"
                  bind:value={conversion.toQuantity}
                />
                {product.unitName}
              </div>
            {/if}
          {/if}
        </div>

        <div class="add-product-dialog__buttons">
          <button class="add-product-dialog__button" onclick={close}
            >Cancel
          </button>
          <button
            class="add-product-dialog__button"
            type="submit"
            onclick={onAdd}
            >Add
          </button>
        </div>
      </div>
    {/if}
  </div>
</div>

<style lang="scss">
  .add-product-dialog {
    position: fixed;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    display: flex;
    padding: 1rem;
    align-items: center;
    justify-content: center;
    background-color: rgba(0, 0, 0, 0.2);
    overflow: hidden;
    z-index: 1000;

    &__wrapper {
      $spacing: 1rem;
      width: 100%;
      max-width: 800px;
      position: relative;
    }

    &__content {
      background-color: white;
      max-height: 100%;
      overflow-y: auto;
      box-shadow: rgba(0, 0, 0, 0.3) 0 3px 8px 3px;
      border-radius: 3px;

      padding: 1rem;
    }

    &__close {
      border: 0;
      background-color: transparent;
      display: block;
      position: absolute;
      right: 1rem;
      top: 1rem;
      z-index: 100;
    }

    &__buttons {
      display: flex;
      justify-content: flex-end;
      padding-top: 1rem;
    }

    &__button {
      margin-left: 1rem;
    }

    &__search-result {
      color: blue;
    }
  }
</style>
