// src/routes/search/SearchBox.svelte
<script
  context="module"
  lang="ts"
>
  export interface SearchParams {
    query: string;
    sortBy: SortBy;
  }
</script>
<script lang="ts">
  import { SortBy } from "$lib";
  import { createEventDispatcher } from "svelte";

  export let isSearching: boolean = false;
  export let searchText: string = '';
  export let sortBy: SortBy = SortBy.NONE;

  const dispatch = createEventDispatcher<{
    search: SearchParams
  }>();

  let onSearch = (event: SubmitEvent): void => {
    event.preventDefault();
    dispatch('search', {
      query: searchText,
      sortBy
    })
  }
</script>

<form on:submit="{onSearch}">
  <input
    name="queryString"
    bind:value={searchText}
  >
  <button
    type="submit"
    disabled={isSearching}
  >{ isSearching ? 'Searching...' : 'Search' }</button>
  <select
    name="sortBy"
    bind:value={sortBy}
    disabled="{isSearching}"
    class="sort-by"
  >
    <option value={SortBy.NONE}>None</option>
    <option value={SortBy.PRICE}>Price</option>
    <option value={SortBy.SPECIAL_OFFERS}>Offers</option>
    <option value={SortBy.SUPERMARKET}>Supermarket</option>
  </select>
</form>

// apps/frontend/src/app/search-box/search-box.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { SortBy } from '@shoppi/api-interfaces';

export interface SearchParams {
  query: string;
  sortBy: SortBy;
}

@Component({
  selector: 'app-search-box',
  templateUrl: './search-box.component.html',
  styleUrls: ['./search-box.component.scss'],
})
export class SearchBoxComponent implements OnInit {
  @Input()
  public isSearching!: boolean;

  @Input()
  public searchText!: string;

  @Input()
  public sortBy!: SortBy;

  @Output()
  public search: EventEmitter<SearchParams> = new EventEmitter();

  public queryString!: string;
  public searchSortBy!: SortBy;

  public SortBy: typeof SortBy = SortBy;

  public ngOnInit() {
    this.queryString = this.searchText || '';
    this.searchSortBy = this.sortBy || SortBy.NONE;
  }

  public onSearch(event: SubmitEvent): void {
    event.preventDefault();
    this.search.emit({
      query: this.queryString,
      sortBy: this.searchSortBy,
    });
  }
}

<form (submit)="onSearch($event)">
  <input
    name="queryString"
    [(ngModel)]="queryString"
  >
  <button type="submit" [disabled]="isSearching">{{ isSearching ? 'Searching...' : 'Search' }}</button>
  <select
    name="sortBy"
    [(ngModel)]="searchSortBy"
    [disabled]="isSearching"
    class="sort-by"
  >
    <option [ngValue]="SortBy.NONE">None</option>
    <option [ngValue]="SortBy.PRICE">Price</option>
    <option [ngValue]="SortBy.SPECIAL_OFFERS">Offers</option>
    <option [ngValue]="SortBy.SUPERMARKET">Supermarket</option>
  </select>
</form>
